Iter9
rutkin/url-shortener pull request #12
Opened 2024-02-28 20:42 UTC by rutkin

2024-03-04 23:12 UTC, valentinsoe requested changes
Спасибо за работу!
Извиняюсь за сроки проверки.
В целом у меня существенных замечаний кроме мидлвары сжатия нет.
Рекомендую исправить, это возможно окажется не так просто, как кажется.

2024-03-04 23:12 UTC, valentinsoe commented on internal/app/handlers/urlhandler.go
> +func (h URLHandler) CreateShorten(w http.ResponseWriter, r *http.Request) error {
При таких названиях CreateURL и CreateShorten - сложно отличить какой из них JSON принимает, а какой нет:)
Рекомендую лучше отображать разницу между функциям в их названиях

2024-03-04 23:12 UTC, valentinsoe commented on internal/app/middleware/compress.go
> +			w.Header().Set("Content-Encoding", "gzip")
В задании есть также условие, что надо сжатие применять только к конкретным Content-Type. А тут применится ко всем:)

2024-03-07 20:20 UTC, rutkin commented on internal/app/handlers/urlhandler.go
> +func (h URLHandler) CreateShorten(w http.ResponseWriter, r *http.Request) error {
Ok

2024-03-07 20:20 UTC, rutkin commented on internal/app/middleware/compress.go
> +			w.Header().Set("Content-Encoding", "gzip")
Ok

2024-03-12 23:10 UTC, valentinsoe approved these changes
Спасибо за исправления.
Осталось убрать хак для тестов 7 инкремента:) Тесты должны проходить без хаков.

2024-03-12 23:10 UTC, valentinsoe commented on internal/app/middleware/compress.go
> +		sync.OnceFunc(func() {
А зачем? Мы в целом можем сколько угодно раз выставить заголовок.

2024-03-12 23:10 UTC, valentinsoe commented on internal/app/middleware/compress.go
> +		if strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") && strings.Contains(r.Header.Get("Content-Encoding"), "gzip") {
Хаки для прохождения тестов нам не нужны:)

2024-03-12 23:11 UTC, valentinsoe requested changes
Промахнулся. Не Approve, а request changes

2024-03-13 10:22 UTC, valentinsoe approved these changes
Спасибо за исправление. Теперь будет другая проблема:)
Написал замечание, рекомендую его почитать.
Но в целом работу принимаю

2024-03-13 10:22 UTC, valentinsoe commented on internal/app/middleware/compress.go
>  	contentType := w.Header().Get("Content-Type")
Это уже почти правильно. 
Только если хендлер не вызовет WriteHeader, а вызовет сразу Write - то мы не сожмем данные.
В начале Write нужен вызов w.WriteHeader()

2024-03-13 10:48 UTC, merged